### ISSUE TITLE
Container based install instructions

### ISSUE THREAD

**Issue by taqtiqa-mark** [peilun-he/PDSim#10]
There are requirements re providing lists of dependencies. In my view this can most easily be met by providing container based install instructions, and a so built container. An R based alternative may be possible but does not achieve the same isolation.

Also, reviewers and potential contributors exploring this software should be able to do so without polluting their system.

**Comment by peilun-he** [comment]
Dependencies have been added: https://github.com/peilun-he/PDSim/commit/558e9f8c40d91d03f58444374e3536bbb6b26e2d

**Comment by taqtiqa-mark** [comment]
I'd prefer a container, but this is not blocking acceptance.  Some projects reject containerization which is fine.

**Comment by peilun-he** [comment]
May I know please if this was accepted? Thank you.

**Comment by taqtiqa-mark** [comment]
I don't believe there is a Dockerfile or some such.  ~~It's up to you if you reject the feature request, leave it for later, or decide to implement it.~~

From my PoV it **is** ~~not~~ blocking.

**Comment by peilun-he** [comment]
Thank you for your feedback, we will be deferring the Dockerfile implementation at this stage. Please note as an alternative we provided the dependencies required for our package. This is a reasonable compromise and we thank you for your agreement. Can you please now close this item? Thank you.

**Comment by taqtiqa-mark** [comment]
>  It's up to you if you reject the feature request, leave it for later, or decide to implement it.

**Comment by taqtiqa-mark** [comment]
Given the amount of my free time I have devoted to this project, I am not willing to spend more time on polluting my system with the installation of software and it's configuration. And then having to clean up the artifacts afterwards.

Given the presence of nuisance parameters will require non-trivial changes to the simulation code, estimation routines and the UI. 

I will have to insist on some sort of isolated environment that "just works", Docker container or VM.

**Comment by peilun-he** [comment]
Dockerfile has been added. The instructions can be found in the "Docker Installation" section.
