### ISSUE TITLE
Conceptual errors

### ISSUE THREAD

**Issue by taqtiqa-mark** [peilun-he/PDSim#11]
- [x] #16
  > We price commodity under arbitrary-free assumption, 
- [x] #17
  > people can earn profits without taking any risk

**Comment by peilun-he** [comment]
Task 1: fixed
Task 2: a citation of definition is added

**Comment by taqtiqa-mark** [comment]
This is related to #12

**Comment by taqtiqa-mark** [comment]
Closing as #12 can track the remaining issues.
