### ISSUE TITLE
No-arbitrage specification: Schwartz-Smith

### ISSUE THREAD

**Issue by taqtiqa-mark** [peilun-he/PDSim#12]
The Schwartz-Smith model is:

![image](https://github.com/peilun-he/PDSim/assets/1468258/42c091c1-b70b-47f1-9d04-99e65d62d22c)

The current project implements a subtly different specification:

![image](https://github.com/peilun-he/PDSim/assets/1468258/c6dec8a1-7779-43ee-80af-7f9f3141fcf8)

The difference should be addressed.

**Comment by peilun-he** [comment]
The following sentence has been add to illustrate the difference to the original Schwartz and Smith's model: 
``In the original Schwartz-Smith model, the parameter $\gamma$ is set to zero. However, in our extended model, we introduce the flexibility for this mean-reversion parameter associated with the long-term factor to take on non-zero values.
``

**Comment by taqtiqa-mark** [comment]
And you claim this is still arbitrage free? 

If so, please cite the proof.

**Comment by peilun-he** [comment]
Please see: https://github.com/peilun-he/PDSim/commit/635cf312bbe0f438b33007af33a3b972ebadfce1. 

4 papers were added as reference. This arbitrage-free pricing (with $\gamma \ne 0$) has been using by some other authors in different futures (Sørensen, 2002) or in crude oil futures but different number of factors (Ames et al., 2020; Cortazar et al., 2019; Cortazar & Naranjo 2006).

**Comment by taqtiqa-mark** [comment]
> Please see: [635cf31](https://github.com/peilun-he/PDSim/commit/635cf312bbe0f438b33007af33a3b972ebadfce1).
> 
> 4 papers were added as reference. This arbitrage-free pricing (with γ≠0) has been using by some other authors in different futures (Sørensen, 2002) or in crude oil futures but different number of factors (Ames et al., 2020; Cortazar et al., 2019; Cortazar & Naranjo 2006).

In light of those references, you need to clarify your following claim, which could be read as an assertion of priority:

> ... in our extended model, we introduce the flexibility for this mean-reversion parameter associated with the long-term factor to take on non-zero values.

Specifically, Isn't this the FP model?  Please clarify who introduced the general model, and if different, who provides the no-arbitrage proof for the unrestricted specification?

**Comment by peilun-he** [comment]
Yes you are right. This is futures pricing model, and it was used  for options in commodity markets. The best reference would be: 

*Cortazar, G., Millard, C., Ortega, H., & Schwartz, E. S. (2019). Commodity price forecasts, futures prices, and pricing models. Management Science, 65(9), 4141-4155.*

Eduardo Schwartz is the co-author of this paper, and not only that, this paper provides a framework with N factors, all of them being OU processes, hence $\gamma_i \ne 0, i = 1, \dots, N$ in general. I will revise my comment of the reference in the paper based on your feedback.
