### ISSUE TITLE
README.md: Polynomial diffusion model

### ISSUE THREAD

**Issue by taqtiqa-mark** [peilun-he/PDSim#13]
This section should cite and place the PD model in the context of Filipovic & Larsson, 2016. Much the same way as the previous section does for Schwart & Smith.

This gives readers some assurance the project is not one more in a long line of mistaken exercises in cranking the handle of some stochastic calculus lemmas.

**Comment by peilun-he** [comment]
This section was rewritten in a similar way as Schwartz and Smith model: https://github.com/peilun-he/PDSim/commit/15d557c69196f01eee39a2b03abd506f25a838af.

**Comment by taqtiqa-mark** [comment]
Apologies for my ambiguity.  If I understand correctly, this implements the Filipovic & Larsson, 2016 results/model.

If that is correct, should you not cite and place the PD model in the context of Filipovic & Larsson, 2016.  Or do you claim to do something novel to Filipovic & Larsson, 2016?

**Comment by taqtiqa-mark** [comment]
The changes made in other issues resolve this issue.
