### ISSUE TITLE
README.md: References

### ISSUE THREAD

**Issue by taqtiqa-mark** [peilun-he/PDSim#15]
I would have been helped by having the references section include (currently it is empty):

- Filipovic, D., & Larsson, M. (2016). Polynomial diffusions and applications in finance. Finance and Stochastics, 20(4), 931–972.
- [Eduardo Schwartz](https://pubsonline.informs.org/action/doSearch?text1=Schwartz%2C+Eduardo&field1=Contrib), [James E. Smith](https://pubsonline.informs.org/action/doSearch?text1=Smith%2C+James+E&field1=Contrib), (2000) Short-Term Variations and Long-Term Dynamics in Commodity Prices. Management Science 46(7):893-911.
https://doi.org/10.1287/mnsc.46.7.893.12034

**Comment by peilun-he** [comment]
We do have a Reference section at the end of the README.md file that includes both references. Or do you mean something else?

**Comment by peilun-he** [comment]
In-text citations are added

**Comment by taqtiqa-mark** [comment]
Can you cite this issue in the relevant PR, or link to the commit where you say this has been fixed?

**Comment by peilun-he** [comment]
Please see: https://github.com/peilun-he/PDSim/commit/b0acb7d79b3e4ecd8d0a5118b245b8a987f2e822
