### ISSUE TITLE
Should be "arbitrage-free"

### ISSUE THREAD

**Issue by peilun-he** [peilun-he/PDSim#16]

**Comment by peilun-he** [comment]
Fixed

**Comment by taqtiqa-mark** [comment]
Can you cite this issue in the relevant PR, or link to the commit where you say this has been fixed?

**Comment by peilun-he** [comment]
Please see: https://github.com/peilun-he/PDSim/commit/515e9656cba97122a1a16aa8eecaa21a33f258f6

**Comment by taqtiqa-mark** [comment]
Happy to close this.
