### ISSUE TITLE
Should be "cannot" and "any" should be removed. Better would be to cite an existing definition of the no-arbitrage condition.

### ISSUE THREAD

**Issue by peilun-he** [peilun-he/PDSim#17]

**Comment by peilun-he** [comment]
A citation of definition is added

**Comment by taqtiqa-mark** [comment]
Can you cite this issue in the relevant PR, or link to the commit where you say this has been fixed?

**Comment by peilun-he** [comment]
Please see: https://github.com/peilun-he/PDSim/commit/bc98404f58956a39ccb067dfc89da80fc86cd74c

**Comment by taqtiqa-mark** [comment]
I've added my comment/suggestion to that commit. It is not showing up likely due to a PR workflow not being used?

I'll track as a separate issue.

**Comment by taqtiqa-mark** [comment]
Happy for this issue to be closed.
