### ISSUE TITLE
Report parameter values

### ISSUE THREAD

**Issue by taqtiqa-mark** [peilun-he/PDSim#22]
https://github.com/peilun-he/PDSim/blob/1d59ab426397af83e989d98fda65ec1be31a5e7c/README.md?plain=1#L654

Without the parameter values for each model it is difficult to interpret these plotted lines.

**Comment by peilun-he** [comment]
Parameter values are added: https://github.com/peilun-he/PDSim/commit/0a61708575690fe1e98f6dc05f8cbd6bcac97390
