### ISSUE TITLE
Nuisance parameters

### ISSUE THREAD

**Issue by taqtiqa-mark** [peilun-he/PDSim#23]
As best I can tell nuisance parameters are present.
This appears when the SS model is represented as a taylor series, so this is likely only evident via some type of limit calculations.
Intrestingly, it also appears nuisance parameters may arise within the FP model when considered on its own.  I leave the authors to work out the details either way.

The following elements will need to be modified to address these explicitly:

- Simulation code
- Estimation code
- UI web elements (particular care is due here to avoid harming unsuspecting users)
- User documents (as above)

**Comment by peilun-he** [comment]
Dear Prof. Van de Vyver,

Many thanks for your comments. I am currently working on them and I should be able to address them in my reply. For this concerned, I understand that a new problem emerged while testing PDSim? May I please know what combinations of parameters (or parameters) are causing a problem?

Thank you.

**Comment by taqtiqa-mark** [comment]
Happy to be shown to be wrong... Doesn't setting various of the $\alpha_i =0$ have the effect of 'knocking out' some of the other parameters?

**Comment by peilun-he** [comment]
For the polynomial diffusion model, setting $\alpha_2 = \alpha_4 = \alpha_5=0$ results in the short-term factor $\chi_t$ disappearing from the spot price equation. Consequently, the spot price and the futures prices become solely dependent on the long-term factor $\xi_t$. Consequently, the parameters associated with $\chi_t$, namely $\kappa, \sigma_{\chi}$, and $\lambda_{\chi}$, do not influence the futures curve in this scenario. This explains the observation of certain parameters "disappearing".

**Comment by taqtiqa-mark** [comment]
Correct, as I pointed out, you have this issue that needs to be addressed. These are nuisance parameters and in general they impact estimation.  I believe you need to address these estimation effects - there is an extensive literature on this and hopefully you won't have to create too many new results?

In addition these parameters affects the choices that naive users are allowed to make.  So this also needs to be reflected in the HTML page UI elements. As well as the unit test suite for those UI elements.

**Comment by peilun-he** [comment]
Hi @taqtiqa-mark thanks for pointing this out. We have added a few error checks to handle this situation. If users set $\alpha_2 = \alpha_4 = \alpha_5 = 0$ (or similarly, $\alpha_3 = \alpha_5 = \alpha_6 = 0$), a modal dialog with an error message is thrown.
