### ISSUE TITLE
Functionality documentation

### ISSUE THREAD

**Issue by bkrayfield** [peilun-he/PDSim#7]
This paper can be improved by adding more documentation on how to use the package outside of the actual method being implemented.

Functionality documentation: Is the core functionality of the software documented to a satisfactory level (e.g., API method documentation)?

**Comment by peilun-he** [comment]
All major functions have been exported. Users can use them outside of the application. A section named "How to Use PDSim (R Script)" gives examples of how to use these functions.

**Comment by bkrayfield** [comment]
@peilun-he Wow, great work adding useful documentation. I am satisfied. Just as a further comment, not mandatory, but you might consider adding another page for some of the more detailed usage, rather than have everything on one page.
