### ISSUE TITLE
Non-blocking: Markdown linting

### ISSUE THREAD

**Issue by taqtiqa-mark** [peilun-he/PDSim#9]
This is unpleasant, but is an entirely subjective professional standard:

![image](https://github.com/peilun-he/PDSim/assets/1468258/99f45f82-1070-4523-ad32-7b8d6ae9520b)

**Comment by peilun-he** [comment]
Fixed. No rules are triggered now. 
<img width="292" alt="mdl" src="https://github.com/peilun-he/PDSim/assets/63130900/c23c9ffd-7ded-4aab-8447-0aa3c6bc5897">
